"""empty message

Revision ID: 74497a66065d
Revises: 9dfac38ddfd9
Create Date: 2021-08-12 23:46:58.426576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74497a66065d'
down_revision = '9dfac38ddfd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.String(), nullable=True))
    op.add_column('Show', sa.Column('venue_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
